<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\InventoryItem;

class POSCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $catalogItems = [
            // 🩺 Medical Services, Lab Tests, Diagnostics & Procedures
            [
                'item_code' => 'SRV-0001',
                'name' => 'General Veterinary Consultation',
                'category' => 'medical_services',
                'description' => 'Comprehensive veterinary physical examination and health assessment.',
                'stock_quantity' => 9999,
                'unit' => 'session',
                'unit_price' => 400.00,
                'cost_price' => 0.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'SRV-0002',
                'name' => 'Emergency / Critical Care Consultation',
                'category' => 'medical_services',
                'description' => 'Immediate triage and stabilization for critical/emergency pet cases.',
                'stock_quantity' => 9999,
                'unit' => 'session',
                'unit_price' => 650.00,
                'cost_price' => 0.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'SRV-0003',
                'name' => 'Follow-up Consultation / Re-check',
                'category' => 'medical_services',
                'description' => 'Re-evaluation of ongoing treatment or surgical recovery.',
                'stock_quantity' => 9999,
                'unit' => 'session',
                'unit_price' => 250.00,
                'cost_price' => 0.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'SRV-0004',
                'name' => 'Complete Blood Count (CBC)',
                'category' => 'medical_services',
                'description' => 'Full hematology test evaluating RBC, WBC, platelets, and hemoglobin.',
                'stock_quantity' => 9999,
                'unit' => 'test',
                'unit_price' => 650.00,
                'cost_price' => 250.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'SRV-0005',
                'name' => 'Blood Chemistry Panel (10-Parameters)',
                'category' => 'medical_services',
                'description' => 'Liver, kidney, protein, and glucose diagnostic profile.',
                'stock_quantity' => 9999,
                'unit' => 'test',
                'unit_price' => 1500.00,
                'cost_price' => 700.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'SRV-0006',
                'name' => 'Digital Ultrasound Examination',
                'category' => 'medical_services',
                'description' => 'High-resolution abdominal or thoracic sonogram evaluation.',
                'stock_quantity' => 9999,
                'unit' => 'procedure',
                'unit_price' => 900.00,
                'cost_price' => 200.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'SRV-0007',
                'name' => 'Digital Radiography / X-Ray (2 Views)',
                'category' => 'medical_services',
                'description' => 'Orthopedic and thoracic digital imaging examination.',
                'stock_quantity' => 9999,
                'unit' => 'procedure',
                'unit_price' => 1200.00,
                'cost_price' => 350.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'SRV-0008',
                'name' => 'Parvovirus / Distemper Rapid Test Kit',
                'category' => 'medical_services',
                'description' => 'Antigen rapid cassette diagnostic test for canine viral infections.',
                'stock_quantity' => 9999,
                'unit' => 'test',
                'unit_price' => 850.00,
                'cost_price' => 400.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'SRV-0009',
                'name' => 'Routine Urinalysis & Sediment Exam',
                'category' => 'medical_services',
                'description' => 'Physical, chemical, and microscopic examination of pet urine.',
                'stock_quantity' => 9999,
                'unit' => 'test',
                'unit_price' => 350.00,
                'cost_price' => 100.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'SRV-0010',
                'name' => 'Fecalysis & Direct Smear Exam',
                'category' => 'medical_services',
                'description' => 'Microscopic detection of gastrointestinal parasites and protozoa.',
                'stock_quantity' => 9999,
                'unit' => 'test',
                'unit_price' => 300.00,
                'cost_price' => 80.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'SRV-0011',
                'name' => 'Inpatient Confinement / Admission (per day)',
                'category' => 'medical_services',
                'description' => '24-hour hospitalized veterinary patient care, monitoring, and fluid therapy.',
                'stock_quantity' => 9999,
                'unit' => 'day',
                'unit_price' => 750.00,
                'cost_price' => 200.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'SRV-0012',
                'name' => 'Dental Prophylaxis & Ultrasonic Scaling',
                'category' => 'medical_services',
                'description' => 'Tartar removal, teeth scaling, and oral cavity polishing under sedation.',
                'stock_quantity' => 9999,
                'unit' => 'procedure',
                'unit_price' => 1800.00,
                'cost_price' => 500.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'SRV-0013',
                'name' => 'Minor Wound Suturing & Debridement',
                'category' => 'medical_services',
                'description' => 'Local anesthesia, cleaning, and surgical closure of lacerations.',
                'stock_quantity' => 9999,
                'unit' => 'procedure',
                'unit_price' => 800.00,
                'cost_price' => 200.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'SRV-0014',
                'name' => 'Spay / Neuter Surgery',
                'category' => 'medical_services',
                'description' => 'Elective sterilization surgery including anesthesia and post-op care.',
                'stock_quantity' => 9999,
                'unit' => 'procedure',
                'unit_price' => 3500.00,
                'cost_price' => 1000.00,
                'reorder_level' => 0,
            ],
            // 💉 Vaccines
            [
                'item_code' => 'VAC-0001',
                'name' => 'Anti-Rabies Vaccine',
                'category' => 'vaccine',
                'description' => 'Mandatory annual immunization against rabies for dogs and cats.',
                'stock_quantity' => 45,
                'unit' => 'vial',
                'unit_price' => 350.00,
                'cost_price' => 180.00,
                'reorder_level' => 10,
            ],
            [
                'item_code' => 'VAC-0002',
                'name' => 'Canine 6-in-1 / 8-in-1 DHPPi+L Vaccine',
                'category' => 'vaccine',
                'description' => 'Distemper, Hepatitis, Parvovirus, Parainfluenza, and Leptospirosis protection.',
                'stock_quantity' => 30,
                'unit' => 'vial',
                'unit_price' => 750.00,
                'cost_price' => 480.00,
                'reorder_level' => 8,
            ],
            [
                'item_code' => 'VAC-0003',
                'name' => 'Feline 4-in-1 (Tricat) Vaccine',
                'category' => 'vaccine',
                'description' => 'Feline Panleukopenia, Rhinotracheitis, Calicivirus core vaccine.',
                'stock_quantity' => 25,
                'unit' => 'vial',
                'unit_price' => 800.00,
                'cost_price' => 520.00,
                'reorder_level' => 6,
            ],
            // ✂️ Grooming Services & Supplies
            [
                'item_code' => 'GRM-0001',
                'name' => 'Full Pet Grooming Package',
                'category' => 'grooming_supply',
                'description' => 'Bath, blow dry, stylish haircut, nail trimming, ear cleaning, and cologne.',
                'stock_quantity' => 9999,
                'unit' => 'session',
                'unit_price' => 650.00,
                'cost_price' => 150.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'GRM-0002',
                'name' => 'Basic Bath & Blow Dry Service',
                'category' => 'grooming_supply',
                'description' => 'Deep cleaning bath with premium shampoo and fluff blow dry.',
                'stock_quantity' => 9999,
                'unit' => 'session',
                'unit_price' => 350.00,
                'cost_price' => 80.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'GRM-0003',
                'name' => 'Medicated Antiparasitic Bath',
                'category' => 'grooming_supply',
                'description' => 'Flea, tick, and fungal therapeutic wash treatment.',
                'stock_quantity' => 9999,
                'unit' => 'session',
                'unit_price' => 450.00,
                'cost_price' => 120.00,
                'reorder_level' => 0,
            ],
            [
                'item_code' => 'GRM-0004',
                'name' => 'Nail Trimming & Ear Cleaning Service',
                'category' => 'grooming_supply',
                'description' => 'Gentle claw clip and antiseptic ear wax flush.',
                'stock_quantity' => 9999,
                'unit' => 'session',
                'unit_price' => 150.00,
                'cost_price' => 30.00,
                'reorder_level' => 0,
            ],
            // 💊 Medicines & Pharmaceuticals
            [
                'item_code' => 'MED-0001',
                'name' => 'Amoxicillin + Clavulanic Acid (Co-Amoxiclav) 250mg',
                'category' => 'medicine',
                'description' => 'Broad-spectrum antibiotic for soft tissue and skin infections.',
                'stock_quantity' => 60,
                'unit' => 'tablet',
                'unit_price' => 45.00,
                'cost_price' => 25.00,
                'reorder_level' => 15,
            ],
            [
                'item_code' => 'MED-0002',
                'name' => 'Doxycycline 100mg Tablet',
                'category' => 'medicine',
                'description' => 'Treatment for tick-borne diseases (Ehrlichia) and respiratory infections.',
                'stock_quantity' => 80,
                'unit' => 'tablet',
                'unit_price' => 40.00,
                'cost_price' => 20.00,
                'reorder_level' => 20,
            ],
            [
                'item_code' => 'MED-0003',
                'name' => 'Prednisone 5mg Tablet',
                'category' => 'medicine',
                'description' => 'Anti-inflammatory corticosteroid tablet.',
                'stock_quantity' => 100,
                'unit' => 'tablet',
                'unit_price' => 20.00,
                'cost_price' => 10.00,
                'reorder_level' => 25,
            ],
            [
                'item_code' => 'MED-0004',
                'name' => 'Gentamicin + Betamethasone Ear Drops (15ml)',
                'category' => 'medicine',
                'description' => 'Topical otic solution for canine and feline ear infections.',
                'stock_quantity' => 24,
                'unit' => 'bottle',
                'unit_price' => 340.00,
                'cost_price' => 210.00,
                'reorder_level' => 6,
            ],
            // 🛍️ Pet Supplies & Accessories
            [
                'item_code' => 'ITM-0009',
                'name' => 'Stainless Steel Non-Skid Pet Bowl (Medium)',
                'category' => 'accessories',
                'description' => 'Durable hygienic stainless steel feeding dish with silicone base.',
                'stock_quantity' => 35,
                'unit' => 'pc',
                'unit_price' => 180.00,
                'cost_price' => 110.00,
                'reorder_level' => 8,
            ],
            [
                'item_code' => 'ITM-0010',
                'name' => 'Nylon Adjustable Dog Leash & Harness Set',
                'category' => 'accessories',
                'description' => 'Heavy-duty breathable chest harness with matching walking lead.',
                'stock_quantity' => 20,
                'unit' => 'set',
                'unit_price' => 320.00,
                'cost_price' => 190.00,
                'reorder_level' => 5,
            ],
            [
                'item_code' => 'ITM-0011',
                'name' => 'Pedigree Adult Beef & Vegetables Dog Food (1.5kg)',
                'category' => 'pet_supplies',
                'description' => 'Complete dry nutrition for adult dogs of all breeds.',
                'stock_quantity' => 25,
                'unit' => 'bag',
                'unit_price' => 380.00,
                'cost_price' => 290.00,
                'reorder_level' => 6,
            ],
            [
                'item_code' => 'ITM-0012',
                'name' => 'Cat Chew Sticks / Dental Treats (5 pcs)',
                'category' => 'pet_supplies',
                'description' => 'Natural matatabi dental chew sticks for feline oral hygiene.',
                'stock_quantity' => 40,
                'unit' => 'pack',
                'unit_price' => 140.00,
                'cost_price' => 75.00,
                'reorder_level' => 10,
            ],
        ];

        foreach ($catalogItems as $data) {
            InventoryItem::updateOrCreate(
                ['item_code' => $data['item_code']],
                $data
            );
        }
    }
}
